### ISSUE TITLE
0.5.2 cannot load projects

### ISSUE THREAD

**Issue by awaddell** [viatra2/IDEA-AWS-Elastic-Beanstalk-Integration#1]
Hi,

Thanks for updating to the latest AWS SDK. Unfortunately, a bug has crept in - on loading IDEA (Ultimate 129.731), there's only a blank panel (I had two projects loaded one of which was the spring-mvc-showcase-war and both were configured to use 0.5.1 of the plugin). 

Restarting gets me to the familiar project menu but projects indicate they're loading yet never do. From here, I can get to the plugin settings and disable the plugin, restart and then load projects. Rinse and repeat the behaviour.

**Comment by viatra2** [comment]
Hello!

We're unable to reproduce your issue, so it looks specific to your project(s). 
To allow us to investigate, please attach idea.log - it could be found with Help->Show log in...

**Comment by awaddell** [comment]
Hi (first time looking at idea.log)
There it is right there - I'm running Java6 (OS X distributed)

2013-07-17 03:15:22,880 [  24537]  ERROR - ij.components.ComponentManager - com/intellij/javaee/awselasticbeanstalk/EBConfiguration : Unsupported major.minor version 51.0 [Plugin: AWS Elastic Beanstalk] 
com.intellij.diagnostic.PluginException: com/intellij/javaee/awselasticbeanstalk/EBConfiguration : Unsupported major.minor version 51.0 [Plugin: AWS Elastic Beanstalk]

**Comment by awaddell** [comment]
Thanks for your help on this. At this stage, please close the ticket and I'll (re) visit the issues surrounding installing Java 7 SDK

**Comment by viatra2** [comment]
We have updated the plugin, now Java 6 is supported.
