### ISSUE TITLE
Config files can also be YAML

### ISSUE THREAD

**Issue by jspiewak** [viatra2/IDEA-AWS-Elastic-Beanstalk-Integration#19]
Contents of a config file need to be detected as they can either be JSON or YAML

**Comment by viatra2** [comment]
Indeed, YAML format for eb extensions config is not currently supported. 
Furthermore such files are processed incorrectly: false warnings are shown, highlight is json-like. Should not affect deployment features though.
![eb_yaml](https://cloud.githubusercontent.com/assets/4850347/4108398/c39282a2-31d6-11e4-9042-081f2e5da6f8.PNG)

**Comment by viatra2** [comment]
Automatic language switch (JSON or YAML) for AWS EB Extensions config files is implemented in version 0.7.3 for IDEA (http://plugins.jetbrains.com/plugin/7274) and version 0.7.2 for Web IDEs (http://plugins.jetbrains.com/plugin/7388)

Please note: autocompletion and structure validation are currently supported only for JSON configs

**Comment by jspiewak** [comment]
Is there anything 14.0 specific about this, or could 0.7.3 could be made to work with IDEA 13.1.x which is build 135.*?

**Comment by viatra2** [comment]
0.7.3 plugin version is not compatible with IDEA 13.1.x because of major changes in IDEA JSON support.
We should consider about backporting this changes to 135.x plugin branch if possible.
