### ISSUE TITLE
Custom InstanceProfile Roles

### ISSUE THREAD

**Issue by haskins-io** [viatra2/IDEA-AWS-Elastic-Beanstalk-Integration#25]
Hi,

I've just noticed that when I deploy an application using the plugin that it overrides the InstanceProfile that is assigned in the Instance configuration page.

I have an environment with an Instance Profile called Lemmings-Instance-Profile, but if I deploy a new version of the application using the plugin it sets the Instance Profile to be the default   aws-elasticbeanstalk-ec2-role  Role.

Is there any way of overriding this action?

Thanks,

Mark

**Comment by viatra2** [comment]
Hello

This is just to let you know that responsible developer is at vacation now, we will look at the issue in 10 days when he is back.

Thanks for using our plugin.

**Comment by viatra2** [comment]
Fixed in build 0.7.6 for IDEA and build 0.6.8 for Web IDEs
