### ISSUE TITLE
Can't deploy an application

### ISSUE THREAD

**Issue by haskins-io** [viatra2/IDEA-AWS-Elastic-Beanstalk-Integration#27]
Hi,

I've updated to PyCharm 4 and now I am no longer able to deploy applications using the plugin. When I try to deploy I get the following:

Deploying 'test-applicatoin'...
Failed to deploy 'test-application': git4idea.GitLocalBranch.getHash()Ljava/lang/String;

I am using PyCharm 4 PY:139-487  and Plugin Version 0.7.3.

When I use my copy of PyCharm 3.4.1 (PY:135-1057) and plugin version 0.6.7  I can deploy as usual.

Thanks,

Mark

**Comment by viatra2** [comment]
Hello, Mark!

Thank you for your feedback. We are already working on this problem.
IDEA Git integration module has some API changes in the latest build.
Please stay tuned - bugfixing update for our plugin should be released soon.

Viatra2

**Comment by viatra2** [comment]
Fixed in build 0.7.7 for IDEA and build 0.7.4 for Web IDEs
