### ISSUE TITLE
How to associate with role

### ISSUE THREAD

**Issue by sheldonh** [viatra2/IDEA-AWS-Elastic-Beanstalk-Integration#28]
How do I associate an app with an IAM role in initial deployment? In my case, the role is what allows the application permission to interact with the DynamoDB it uses.

**Comment by viatra2** [comment]
IAM role option was added in 0.8.0 release.

**Comment by uvwild** [comment]
In my IDEA 14.1 the IAM role option is grayed out and I wonder how to use it as without this setting the deployment of  my war fails. Is the configuration somewhere else accessible (preferably file) except for the Run Configuration Menu?
