### ISSUE TITLE
Update yoda-time

### ISSUE THREAD

**Issue by giurim** [viatra2/IDEA-AWS-Elastic-Beanstalk-Integration#36]
Deploying fails when IntelliJ runs on Java8 with a 403 error about a wring timestamp in the S3 request. After changing yoda-time dependency in my plugin (and deleting IntelliJ cache) to the newest it works. Related: https://github.com/aws/aws-sdk-java/issues/444

**Comment by viatra2** [comment]
We've updated the dependency in the recently released 0.8.1
