### ISSUE TITLE
Debug not working if beanstalk not in default VPC

### ISSUE THREAD

**Issue by mrjoe7** [viatra2/IDEA-AWS-Elastic-Beanstalk-Integration#39]
When I try to debug beanstalk application that is non in default VPC I get error message

> Failed to deploy 'register:war': com.amazonaws.AmazonServiceException: The security group 'sg-223b504b,sg-b13d56d8' does not exist in default VPC 'vpc-a130ebc8' (Service: AmazonEC2; Status Code: 400; Error Code: InvalidGroup.NotFound; Request ID: a7c774b0-b4f9-432f-a6d2-6f4df40436c5)

Beanstalk instance I want to debug is running in VPC vpc-bc0582d5, my default VPC is vpc-a130ebc8.
Deployment without debug is working just fine.

My plugin run configuration:
![settings](https://cloud.githubusercontent.com/assets/16738219/14707997/3066c104-07c8-11e6-9089-68927ca36dcf.jpg)

**Comment by hamx0r** [comment]
This may be fixable by adding a folder in the root of your project called `.ebextensions` and then a file ending in `.config` (like `deployment.config`) with the following contents:

```
{
  "option_settings": [
    {
      "namespace": "aws:ec2:vpc",
      "option_name": "VPCId",
      "value": "vpc-bc0582d5"
    }
  ]
}
```
