### ISSUE TITLE
com.amazon.AmazonClientException: Unable to execute HTTP request: peer not authenticated

### ISSUE THREAD

**Issue by johnoa** [viatra2/IDEA-AWS-Elastic-Beanstalk-Integration#7]
Hi

IntelliJ: 13.0.1
OS X: 10.9.1

Upgraded to latest version of Mavericks, now receive the following when I try to deploy through the AWS ElasticBeanStalk plugin.  Believe this might be related to the SSL changes Apple have made.  

Error message in IntelliJ:

com.amazon.AmazonClientException: Unable to execute HTTP request: peer not authenticated

Regards
John

**Comment by viatra2** [comment]
For now, it looks like not related to the plugin but to the system setup. Yet we are going to investigate further.

**Comment by johnoa** [comment]
Thanks.  Think it might be to do with how Apple are using the keychain access for certificate storage.  Let me know if I can help look into this.

**Comment by viatra2** [comment]
I have found similar SSL "peer not authenticated" issue with Mavericks here: https://issues.sonatype.org/browse/OSSRH-7630. It was stated that "After reinstalling the Java SE 6 Developer JDK from Apple it worked again". So maybe you should try to reinstall JDK but I am still not sure if it will help in your case.

To avoid JDK reinstallation you can try bundled IDEA distribution: http://download-ln.jetbrains.com/idea/ideaIU-13.0.1-jdk-bundled.dmg. This distribution already contains JDK7 (JDK6 is used by default by regular IDEA 13 OS X distro).

**Comment by johnoa** [comment]
Just to let you know that I have switched to the bundled IDEA distribution and it is now working correctly.  Thanks for your time on this and for developing such a useful plugin.  Cheers.

**Comment by viatra2** [comment]
Good to know! 

It may be interesting for you to know that we are working on the new update including additional solution stacks support (PHP, Ruby, Python, Node.js) and incremental deploy (via git). And we expect it to be release at the end of this week, stay tuned.
We would appreciate a good rating at the http://plugins.jetbrains.com/plugin/7274 :)

**Comment by viatra2** [comment]
New version 0.6.0 is released and includes following improvements:
- module deployment is used to deploy all non-java solution stacks (PHP, Ruby, Python, Node.js) - project contents are uploaded to S3 and deployed on chosen environment configuration
- java exploded WARs are supported
- incremental deploy via git is implemented for modules and exploded WARs - now only changes are uploaded
- plugin does not bundle AWS SDK anymore, all needed libraries are downloaded in runtime

Please update to the latest version from IDEA plugin manager or download it from the plugin page: http://plugins.jetbrains.com/plugin/7274
